# yaml表示以上对象
person:
  userName: zhangsan
#  userName: "zhangsan \n 张三"
#  userName: 'zhangsan \n 张三'
#  单引号会将 \n 作为字符串输出, 双引号会将\n 作为 换行输出
#  即 双引号不会转义, 单引号会转义
  boss: false
  birth: 2020/1/1
  age: 18
  pet:
    # 使用缩进式给 pet 对象赋值
    name: tomcat
    weight: 23.4
    # 行内给 interests 字符串数组赋值
  interests: [篮球,游泳]
  # 使用缩进式给 animal list集合赋值
  animal:
    - jerry
    - mario
  # 使用缩进式给 score map<String,Object>集合赋值
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  # 使用缩进式给 allPets map<String,List<Pet>>集合赋值
  allPets:
    sick:
      - {name: tom}
      - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]



